version: "{build}"
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform

  - node --version
  - npm --version
  - jspm --version
test_script:
  - ps: npm install
build: off