version: "{build}"
environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "13"
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform

  - node --version
  - npm --version
test_script:
  - ps: npm install
build: off